### ISSUE TITLE
[Feature Request]: fisher compatibility

### ISSUE THREAD

**Issue by sourajit02** [sshilovsky/fish-helix#4]
Very simple change to make this plugin compatible with the fish plugin manager [jorgebucaran/fisher](https://github.com/jorgebucaran/fisher): simply have to move the `*.fish` files into a directory called `functions`.

**Comment by sshilovsky** [comment]
Pushed. Let me know if it doesn't work.

**Comment by sourajit02** [comment]
Thanks, for the prompt update and for the plugin itself! It works on my end.
